title: httpout
description: httpout allows you to execute your Python script from a web URL, the print() output goes to your browser.
theme: just-the-docs

url: https://httpout.github.io

aux_links:
  Template Repository: https://github.com/httpout/httpout.github.io

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
